# REST settings
rest:
  url: 'https://leox.derkurier.de:13000/rs/api'
  # Ignores SSL certificate
  ssl-validation: false

# Database settings
database:
  # Automatically removes SQLite database on startup
  clean-startup: false

# Update service settings
update:
  bundle-name: 'leoz-mobile'
  version-alias: 'snapshot'
  force: false