# User settings
user:
   idle-timeout-minutes: 240

# Peer connectivity settings
remote:
   host: 'leoz-demo.derkurier.de'

   # Http related settings
   http:
      port: 13000
      ssl: true

   # Mq broker related settings
   broker:
      native-port: 13001

# Database settings
database:
   # Automatically removes SQLite database on startup
   clean-startup: false

# Update service settings
update:
   enabled: true
   bundle-name: 'leoz-mobile'
   # Version alias override should not be set for productive versions
   # This setting is still required when testing on dev/integration servers
   # version-alias: 'snapshot'
   force: false
   # Cycle period in seconds
   period: 3600

   remote:
      host: 'leoz.derkurier.de'
      http:
         port: 13000
         ssl: true

# Location service settings
location:
   enabled: true
   # Minimum distance in meters
   minDistance: 75
   force: true
   # Period in seconds
   period: 20
   allow-mock-location: false

# Developer/debug settings
debug:
   enabled: false
   allow-developer-options: true
   # By default free screen rotation is not allowed and controlled per screen
   user-screen-rotation: false
   # Enables synthetic aidc inputs, available via screen menu
   synthetic-aidc-enabled: true