# REST settings
rest:
  url: 'http://192.168.0.28:13000/rs/api'
  # Ignores SSL certificate
  ssl-validation: true

# Database settings
database:
  # Automatically removes SQLite database on startup
  clean-startup: false

# Update service settings
update:
  bundle-name: 'leoz-mobile'
  version-alias: 'snapshot'
  force: false