// lang-de.ts
export const LANG_DE_TRANS = {
  'login': 'Anmeldung',
  'username': 'Benutzername',
  'username is required': 'Benutzername muss angegeben werden',
  'User does not exist': 'Benutzername existiert nicht',
  'User authentication failed': 'Anmeldung fehlgeschlagen',
  'password': 'Kennwort',
  'password is required': 'Kennwort muss angegeben werden',
  'btlogin': 'anmelden',
  'home': 'Startseite',
  'footer': 'Fussbereich',
  'dispo': 'Dispo',
  'tour': 'Tour',
  'management': 'Management',
  'users': 'Mitarbeiter',
  'logout': 'Abmelden',
  'firstname': 'Vorname',
  'surname': 'Nachname',
  'email': 'Email',
  'phone': 'Telefon',
  'alias': 'Alias',
  'role': 'Rolle',
  'active': 'Aktiv',
  'inactive': 'nicht aktiv',
  // 'FirstnameMinLength': 'Der Vorname muss aus mindestens 3 Zeichen bestehen',
  'FirstnameMaxLength': 'Der Vorname darf maximal 45 Zeichen lang sein',
  // 'SurnameMinLength': 'Der Nachname muss aus mindestens 3 Zeichen bestehen',
  'SurnameMaxLength': 'Der Nachname darf maximal 45 Zeichen lang sein',
  // 'PwdMinLength': 'Das Kennwort muss aus mindestens 5 Zeichen bestehen',
  'PwdMaxLength': 'Das Kennwort darf nicht mehr als 25 Zeichen haben',
  // 'EmailMinLength': 'Die Emailadresse muss aus mindestens 3 Zeichen bestehen',
  // 'EmailMaxLength': 'Die Emailadresse darf nicht mehr als 100 Zeichen haben',
  'PhoneMaxLength': 'Die Telefonnummer darf nicht mehr als 45 Zeichen haben',
  // 'AliasMinLength': 'Alias muss aus mindestens 3 Zeichen bestehen',
  'AliasMaxLength': 'Alias darf maximal 30 Zeichen lang sein',
  'save': 'Speichern',
  'clear': 'Leeren',
  'Poweruser': 'Extrem-Benutzer',
  'User': 'Benutzer',
  'Driver': 'Fahrer',
  'Customer': 'Kunde',
  'EmailFormat': 'Kein korrektes Format der E-Mailadresse',
  'duplicate email': 'Die E-Mailadresse existiert bereits.'
};

