// lang-en.ts
export const LANG_EN_TRANS = {
  'login': 'Login',
  'username': 'Username',
  'username is required': 'Username is required',
  'User does not exist': 'User does not exist',
  'User authentication failed': 'User authentication failed',
  'password': 'Password',
  'password is required': 'Password is required',
  'btlogin': 'login',
  'home': 'Home',
  'footer': 'Footer',
  'dispo': 'Dispo',
  'tour': 'Tour',
  'management': 'Management',
  'users': 'Users',
  'logout': 'Logout',
  'firstname': 'First Name',
  'surname': 'Surname',
  'email': 'Email',
  'phone': 'Phone',
  'alias': 'Alias',
  'role': 'Role',
  'active': 'Active',
  'inactive': 'Inactive',
  // 'FirstnameMinLength': 'Firstname needs to be at least 3 characters long',
  'FirstnameMaxLength': 'Firstname cannot exceed 45 characters',
  // 'SurnameMinLength': 'Surname needs to be at least 3 characters long',
  'SurnameMaxLength': 'Surname cannot exceed 45 characters',
  'PwdMinLength': 'Password needs to be at least 5 characters long',
  'PwdMaxLength': 'Password cannot exceed 25 characters',
  // 'EmailMinLength': 'Email needs to be at least 3 characters long',
  // 'EmailMaxLength': 'Email cannot exceed 100 characters',
  'PhoneMaxLength': 'Phone cannot exceed 45 characters',
  // 'AliasMinLength': 'Alias needs to be at least 3 characters long',
  'AliasMaxLength': 'Alias cannot exceed 30 characters',
  'save': 'Save',
  'clear': 'Clear'
};
