export const LANG_DE_TRANS = {
  // login form
  'login': 'Anmeldung',
  'username': 'Benutzername',
  'btlogin': 'anmelden',
  'username is required': 'Benutzername muss angegeben werden',
  'User does not exist': 'Benutzername existiert nicht',
  'User authentication failed': 'Anmeldung fehlgeschlagen',
  'password': 'Kennwort',
  'password is required': 'Kennwort muss angegeben werden',
  'loggedinas': 'Angemeldet als',
  'On login-change you have to provide a password': 'Bei Änderungen geben Sie bitte Ihr Passwort ein.',
  // menu
  'home': 'Startseite',
  'lists': 'Listen',
  'footer': 'Fussbereich',
  'scans': 'Scans',
  'driver-assignment': 'Fahrerzuordnung',
  'driver': 'Driver',
  'forStation': 'für Station',
  'orders': 'Aufträge',
  'recording': 'Erfassung',
  'action dispatch': 'Aktionsversand',
  'standing orders': 'Daueraufträge',
  'disposition': 'Disposition',
  'inbound disposition': 'Inbound-Disposition',
  'tour planning': 'Tourenplanung',
  'tour optimization': 'Tourenoptimierung',
  'outbound disposition': 'Outbound-Disposition',
  'reprint stoplist': 'Nachdruck Stopliste',
  'scanning': 'Scannung',
  'inbound scan': 'Inbound-Scan',
  'outbound scan': 'Outbound-Scan',
  'depot entry': 'Depoteingang',
  'stoplist scan': 'Stopplisten-Scan',
  'track & trace': 'Track & Trace',
  'shipment information': 'Sendungsinformation',
  'vehicle tracing': 'Spurverfolgung',
  'stoplist backinput': 'Stopplistenrückerfassung',
  'shipment cockpit': 'Sendungscockpit',
  'line haul': 'Line Haul',
  'administration': 'Verwaltung',
  'customer administration': 'Kundenverwaltung',
  'user administration': 'Mitarbeiterverwaltung',
  'addresspool': 'Adresspool',
  'mobileX': 'mobileX',
  'settings': 'Einstellungen',
  'startpage': 'Startseite',
  'communication': 'Kommunikation',
  'printer administration': 'Druckerverwaltung',
  'comports': 'Comports',
  'interfaces': 'Interfaces',
  'addons': 'Zubehör',
  'routing': 'Routing',
  'stationfinder': 'Standortliste',
  'datafilter': 'Datenfilter',
  'print lists': 'Listendruck',
  'search location': 'Ortssuche',
  'export/import data': 'Datenexport/-import',
  'request data': 'Data Requester',
  'statistics': 'Statistik',
  'quality': 'Qualität',
  'logout': 'Logout',
  // 'statistics': 'Statistiken', (see below)
  'pod-reprints': 'Rollkarten Nachdruck',
  'client-management': 'Kundenverwaltung',
  'client-data': 'Kundendaten',
  'periodic-shipments': 'Daueraufträge',
  'promotion-shipments': 'Aktionsversand',
  'office-management': 'Büroverwaltung',
  'printer-setup': 'Drucker einrichten',
  'password-management': 'Kennwortverwaltung',
  'directinfo-to-partner': 'Direktinfo an Partner',
  'supportrequest': 'Supportanfrage',
  'notification': 'Avisierung',
  'accessoires': 'Zubehör',
  'stationlist': 'Depotliste',
  'townsearch': 'Orte suchen',
  'dataexport': 'Datenexport',
  'documents': 'Dokumente',
  'calendar': 'Kalender',
  'tracking': 'Tracking',
  'tour': 'Tour',
  'management': 'Management',
  'co-worker': 'Mitarbeiter',
  // user form
  'firstname': 'Vorname',
  'surname': 'Nachname',
  'email': 'Email',
  'emailOrLogin': 'Email/Login',
  'phone': 'Telefon',
  'alias': 'Alias',
  'aliasOrDriver': 'Alias/FahrerNr',
  'role': 'Rolle',
  'active': 'Aktiv',
  'inactive': 'nicht aktiv',
  // 'FirstnameMinLength': 'Der Vorname muss aus mindestens 3 Zeichen bestehen',
  'FirstnameMaxLength': 'Der Vorname darf maximal 45 Zeichen lang sein',
  // 'SurnameMinLength': 'Der Nachname muss aus mindestens 3 Zeichen bestehen',
  'SurnameMaxLength': 'Der Nachname darf maximal 45 Zeichen lang sein',
  'PwdMinLength': 'Das Kennwort muss aus mindestens 6 Zeichen bestehen',
  'PwdMaxLength': 'Das Kennwort darf nicht mehr als 25 Zeichen haben',
  // 'EmailMinLength': 'Die Emailadresse muss aus mindestens 3 Zeichen bestehen',
  // 'EmailMaxLength': 'Die Emailadresse darf nicht mehr als 100 Zeichen haben',
  'PhoneMaxLength': 'Die Telefonnummer darf nicht mehr als 45 Zeichen haben',
  // 'AliasMinLength': 'Alias muss aus mindestens 3 Zeichen bestehen',
  'AliasMaxLength': 'Alias darf maximal 30 Zeichen lang sein',
  'save': 'Speichern',
  'clear': 'Leeren',
  'Admin': 'Admin',
  'Poweruser': 'Extrem-Benutzer',
  'User': 'Benutzer',
  'Driver': 'Fahrer',
  'Customer': 'Kunde',
  'EmailFormat': 'Kein korrektes Format der E-Mailadresse',
  'duplicate email': 'Die E-Mailadresse existiert bereits.',
  'expires_on': 'Gültig bis',
  'user account deactivated': 'Ihr Konto ist deaktiviert',
  'yes': 'ja',
  'no': 'nein',
  'UserInsertSuccessful': 'Benutzer erfolgreich angelegt',
  'UserUpdateSuccessful': 'Benutzer erfolgreich geändert',
  'UserSuccessfulDeactive': 'Benutzer erfolgreich deaktiviert',
  'apprights': 'App Berechtigungen',
  'hub': 'HUB',
  'route': 'Linie',
  'station': 'Station',
  'line': 'Line',
  'homebase': 'Home',
  'forExample': 'z.B.:',
  'egMail': 'FahrerNr@StationNr',
  // map form
  'allusers': 'alle Mitarbeiter',
  'drivers': 'Fahrer',
  'alldrivers': 'alle Fahrer',
  'could not get geolocation points': 'Keine Geokoordinaten gefunden',
  'could not get route': 'Keine Route gefunden',
  'name': 'Name',
  'vehicle': 'Fahrzeug',
  'phoneoffice': 'Telefon Büro',
  'phonemobile': 'Telefon Mobil',
  'lastactivity': 'letzte Aktivität',
  'bike': 'Fahrrad',
  'car': 'PKW',
  'van': 'Bus',
  'truck': 'LKW',
  'unknown': 'unbekannt',
  'last': 'Letzte',
  'hs': 'Std',
  'refreshevery': 'Aktualisieren alle',
  'mins': 'Min',
  'latestRefresh': 'Zuletzt aktualisiert',
  'showlist': 'Liste ein-/ausblenden',
  'selectedformap': 'Ausgewählt für Karte',
  'day': 'Tag',
  // stationloading form - loadinglist
  'loadingcontrol': 'Verladesteuerung',
  'newloadlist': 'Neue Ladeliste',
  'payload': 'Zuladung in Kg',
  'exportdate': 'Versanddatum',
  'loadlist': 'Ladeliste',
  'printlabel': 'Label',
  'alllists': 'alle',
  'selectedlist': 'für Auswahl',
  'actuallist': 'aktuell',
  'preview': 'Vorschau',
  'printpreview': 'Druckvorschau',
  'directprint': 'Sofortdruck',
  'information': 'Information',
  'loadlistnumber': 'Ladelisten Nr',
  'loadedweight': 'geladene (Kg)',
  'freeweight': 'noch frei (Kg)',
  'stillopen': 'noch offen',
  'packcount': 'Anzahl PkSt',
  'weight': 'Gewicht',
  'loaded': 'geladen',
  'notloaded': 'offen',
  'packages': 'Packstücke',
  'scanmsgfield': 'Scan Nachrichten',
  'scanfield': 'Scanfeld',
  'loadinglistscan': 'Ladelistenscan',
  'bagscan': 'Bagscan',
  'zip': 'PLZ',
  'city': 'Ort',
  'devliveryStation': 'Lieferdepot',
  'loadinglistNo': 'Ladelisten Nr',
  'loadinglist': 'Ladeliste',
  'wrapperType': 'Verpackungsart',
  'valore': 'Valore',
  'print': 'Drucken',
  'noAction': 'keine Aktion ausgewählt',
  'actionNewLoadlist': 'Aktion: Neue Ladeliste',
  'actionChangePayload': 'Aktion: Änderung der Zuladung',
  'actionChangeLoadlist': 'Aktion: Wechsel Ladeliste',
  'notOnLoadlist': 'noch nicht auf Ladeliste',
  'onLoadlist': 'bereits geladen',
  'noDataAvailable': 'keine Einträge vorhanden',
  'no activeLoadinglist': 'keine Ladeliste ausgewählt',
  // stationloading form - bagscan
  'openOnBaglist': 'noch nicht auf Bagliste',
  'bagInformation': 'Bag Information',
  'bagID': 'Bag-ID',
  'backLabel': 'Rücklabel',
  'backSeal': 'Rückplombe',
  'yellow': 'gelb',
  'packNumber': 'Packstücknummer',
  'messages': 'Meldungen',
  'llNo': 'LL-Nr',
  'valCount': 'Anzahl Valoren',
  'bagWeightKg': 'Baggewicht (Kg)',
  'completeProcessingF5': 'Bearbeitung abschliessen (F5)',
  'swapSealF10': 'Tausch auf Notfallplombe (F10)',
  'update': 'Aktualisieren',
  'noLlNoSet': 'Keine Ladelistennummer gesetzt',
  'noScan': 'kein Scan',
  'alreadyScanned': 'bereits gescannt',
  'noAlreadyScanned': 'Diese Belegnummer wurde bereits gescannt.',
  'transferedToOtherLoadlist': 'Diese Belegnummer wurde bereits auf eine andere Ladeliste gescannt und wird jetzt umgebucht.',
  'noDataInDatabase': 'Kein Datensatz vorhanden.',
  'depotMismatch': 'Nicht scanbar, da Sie für diese Sendung nicht das abholende Depot sind.',
  'invalidSenddate': 'Das Verladedatum der Sendung entspricht nicht den vorgegebenen Kriterien. ' +
  'Bitte in der Auftragserfassung nachbearbeiten.',
  'invalidProduct': 'Diese Sendung ist kein <ONS>. Scan nicht möglich. Bitte in der Auftragserfassung nachbearbeiten.',
  'noValoreScan': 'Dieses Packstück ist eine Valore. Scan nicht möglich. Valoren müssen in einen Bag gescannt werden.',
  'baglist': 'Bagliste',
  'bagCountMsgfield': 'Ihr Bag-Bestand überschreitet Ihr Kontingent.' + '<br>' +
                      'Bitte senden Sie zur Entlastung 3 Bags zurück.',
  'infoMsgfield': 'Belegscanfeld öffnen mit F2.' + '<br>' +
                      'Felder leeren mit F3.' + '<br>' +
                      'Bearbeitung abschliessen mit F5.' + '<br>' +
                      'Tausch auf Notfallplombe mit F10.',
  'maxBagWeightReached': 'Maximalgewicht erreicht',
  'caution': 'Achtung',
  'activateBlueSeal': 'Aktivieren der blauen Plombe, wenn Sie einen wichtigen Grund haben',
  'scanBlueSeal': 'Scan Notfallplombe (blau)',
  'reason': 'Grund',
  'saveF7': 'Speichern (F7)',
  'noBagIDSet': 'Das Feld <Bag-ID> darf nicht leer sein',
  'noBackLabelSet': 'Das Feld <Rücklabel> darf nicht leer sein',
  'noBackSealSet': 'Das Feld <Rückplombe (gelb)> muss leer sein',
  'noSealActivation': 'Sie können keine Notfallplombe aktivieren, wenn Sie bereits eine gültige Rückplombe angegeben haben.',
  'noBlueSealNoSet': 'Das Feld <Scan Notfallplombe (blau)> darf nicht leer sein',
  'noReasonSet': 'Das Feld < Grund > darf nicht leer sein',
  'clearFields': 'Felder leeren',
  // reports
  'report_loadinglist': 'Ladeliste',
  'date': 'Datum',
  'to_auf': 'auf',
  'from': 'von',
  'to_nach': 'nach',
  'total_CountShipments': 'Gesamtanzahl Sendungen',
  'total_CountPackages': 'Gesamtanzahl Packstücke',
  'total_Weight': 'Gesamtgewicht',
  'totalPackagesToTransport': 'Folgende Packstücke wurden zum Transport unbeschädigt übernommen',
  'nameOfDriver': 'Name des Fahrers',
  'licensePlate': 'KFZ-Kennzeichen',
  'loadingDate': 'Datum',
  'loadingTime': 'Uhrzeit',
  'signature': 'Unterschrift',
  'llDriver': '(Unternehmer/Fahrer)',
  'page': 'Seite',
  'printingDate': 'Druckdatum',
  // importscan form - importscan quick - importscan check
  'newShipment': 'Nacherfassen',
  'allShipments': 'Alle Sendungen',
  'controlscan': 'Kontrollscan',
  'listprinting': 'Listendruck',
  'sortorder': 'Sortierung',
  'standard': 'Standard',
  'importlist': 'Importliste',
  'quickscan': 'Quickscan',
  'refresh': 'Aktualisieren',
  'to': 'nach',
  'typeOfPackaging': 'Verpackungsart',
  'parcelno': 'PkSt Nr',
  'packs': 'PkSt',
  'vol-Weight': 'Vol Gew.',
  'real-Weight': 'Real Gew.',
  'length': 'Länge',
  'width': 'Breite',
  'height': 'Höhe',
  'import_controllist': 'Import Kontrollliste',
  // deliveryscan form
  'deliverylistscan': 'Rollkartenscan',
  'tourno': 'Tour Nr',
  'deliverydate': 'Lieferdatum',
  'help': 'Hilfe',
  'newDeliverylist': 'neue Rollkarte',
  'deliverylistno': 'Rollkarten Nr',
  'sortZip': 'nach PLZ',
  'sortDeadline': 'nach Termin',
  'withImportScan': 'mit Importscan',
  'justforDeliverydate': 'nur für Lieferdatum',
  'justActualTour': 'nur aktuelle Tour',
  'tourNo': 'Tour Nr',
  'deliverylistNo': 'Rollkarten Nr',
  'shipmentCount': 'Anzahl Sdg',
  'packageCount': 'Anzahl PkSt',
  'afternoon': 'Nachmittag',
  'free': 'Frei',
  'realWeight': 'Realgewicht',
  'volumeWeight': 'Volumengewicht',
  'effectiveWeight': 'Effektivgewicht',
  'sorting': 'Sortierung',
  // deliveryscan list, delivery dispo
  'pos': 'Pos',
  'consignee': 'Empfänger',
  'deadline': 'Termin',
  'shipmentno': 'Sdg Nr',
  'deliverystatus': 'Status',
  'deliverycode': 'Code',
  'shipment': 'Sdg',
  'count': 'Anzahl',
  'expected': 'zu Erwartende',
  'throughHub': 'durch HUB',
  'onTruck': 'im Linienfahrzeug',
  'withImportscan': 'mit Importscan',
  'filter': 'Filter',
  'uptoDeliverydate': 'bis Lieferdatum',
  'forDeliverydate': 'für Lieferdatum',
  'withStock': 'mit Lager',
  'select': 'Select',
  'hidePU': 'PickUps ausblenden',
  'glsDelivery': 'GLS Zustellung',
  'allTours': 'alle Touren',
  'justForTour': 'nur für Tour',
  'predispo': 'Vordisposition',
  'detailedDispo': 'Detail Disposition',
  'street': 'Strasse',
  'vol.': 'Vol.',
  'shipmentNo': 'Sendungs Nr',
  'tourdispo': 'Tourdisposition',
  'tourinfo': 'Tourinformtion',
  'rk': 'RK',
  'tour-deliverydispo': 'Tour/Rollkarten Dispo',
  'deliveryinfo': 'Rollkarteninformation',
  // ipointlist, ipointquick
  'scan_without_validating': 'Scan ohne Prüfung',
  'ipointlist': 'I-Punkt Liste',
  'ipoint_quickscan': 'I-Punkt Quickscan',
  'total_real_Weight': 'Gesamt Realgewicht',
  'total_vol_Weight': 'Gesamt Vol. Gewicht',
  'ipointListcan': 'I-Punkt Listenscan',
  'packages_to_scan': 'Packstücke zu scannen',
  // tourzipmapping
  'tourzipmapping': 'Tour/PLZ Zuordnung',
  'driverNo': 'Fahrer Nr',
  'drivername': 'Fahrername',
  'fromZip': 'von PLZ',
  'toZip': 'nach PLZ',
  'setnewArea': 'neuen Bereich festlegen',
  // orderform
  'consignor': 'Absender',
  'client': 'Kunde',
  'consignorClientNos': 'Abs.Nr (F11)',
  'consigneeClientNos': 'Empf.Nr (F12)',
  'consignorClientReNos': 'KdNr-RE',
  'customer': 'Kunde',
  'reference': 'Referenz',
  'pickup': 'Pickup',
  'senderLine1': 'Absender Zeile 1',
  'senderLine2': 'Absender Zeile 2',
  'senderLine3': 'Absender Zeile 3',
  'pickupTimeWindow': 'Zeiten',
  'serviceF7': 'Service (F7)',
  'serviceF8': 'Service (F8)',
  'pickupInfo': 'Info',
  'pickupContact': 'Kontakt',
  'clientInvoice': 'KD-RE (F4)',
  'delivery': 'Zustellung',
  'deliveryLine1': 'Empfänger Zeile 1',
  'deliveryLine2': 'Empfänger Zeile 2',
  'deliveryLine3': 'Empfänger Zeile 3',
  'deliveryTimeWindow': 'Zeiten',
  'deliveryInfo': 'Info',
  'deliveryContact': 'Kontakt',
  'system': 'System',
  'orderform': 'Auftragserfassung',
  'orderlist': 'Auftragsliste',
  'CC': 'LKZ',
  'No': 'Nr',
  'orderingParty': 'Auftraggeber',
  'collector': 'Abholer',
  'deliverystation': 'Lieferstation',
  'pickupdate': 'Abholdatum',
  'until': 'bis',
  'fixPickup': 'Fix Abholung',
  'realweight': 'Realgewicht',
  'volweight': 'Volumengewicht',
  'payweight': 'Frachtpflichtiges Gewicht',
  'exportcosts': 'Exportkosten (PU)',
  'description': 'Beschreibung',
  'productvalue': 'Warenwert',
  'liabilityvalue': 'Haftungswert',
  'insurance': 'Versicherung',
  'total': 'Gesamt',
  'pickupInfoDispo': 'Abholinfo Dispo',
  'XChRetNo': 'X-Change Ret.Nr',
  'accountingClient': 'Abrechnung Kunde',
  'fixDelivery': 'Fix Zustellung',
  'importcosts': 'Importkosten',
  'content': 'Inhalt',
  'cod': 'Nachnahme',
  'infoDeliverylist': 'Info Rollkarte',
  'deliveryInfoDispo': 'Zustellinfo Dispo',
  'shipmentF3': 'Sendung (F3)',
  'package-No': 'Packstück-Nr',
  'productSpecification': 'Produktspezifikation',
  'products': 'Produkte',
  'distanceDirectKM': 'Entfernung (Direkt)',
  'ad_hoc_CostsF5': 'ad hoc Preis (F5)',
  'verify': 'Prüfen',
  'saveF2': 'Speichern (F2)',
  'newStrgN': 'Neu (Strg+N)',
  'delete': 'Löschen',
  'printF9': 'Drucken (F9)',
  'label': 'Label',
  'waybill': 'Frachtbrief',
  'PickUp': 'Pick Up',
  // orderlist
  'senddate': 'Verladedatum',
  'avisnumber': 'Avisnummer',
  'shipmentoverview_max_10_days': 'Sendungsübersicht (max. 10 Tage)',
  // statusbar
  'not_connected_to_leoz': 'nicht mit leoz verbunden',
  'connected_to_leoz': 'mit leoz verbunden',
  // touroptimizing
  'touroptimizing': 'Touroptimierung',
  'stoplist': 'Stopliste',
  'deliverylists': 'Zustelllisten',
  'tourlists': 'Tourlisten',
  'mark_all_none': 'Alle/Keine markieren',
  'none': 'Keine',
  'all': 'Alle',
  'optimize': 'Optimieren',
  'driverlists': 'Fahrerlisten',
  'tours-most-likely-outdated': 'Ihre Rollkarten haben sich geändert. ' +
                                'Um sicherzustellen, dass Sie auf dem neuesten Stand sind, sollten Sie "reset" drücken',
  'optimization_progress': 'Optimierung läuft...',
  'optimizing_optimized_tours_not_possible': 'Optimierung optimierter Touren nicht möglich',
  'optimizationOptions': 'Optimierungsoptionen',
  'cancel': 'Abbruch',
  'start': 'Start',
  'no_optimizable_tours_selected': 'Keine optimierbaren Touren ausgewählt',
  'optimizeTodayAndFuture': 'Tourstart heute',
  'optimizeTraffic': 'Verkehrslage berücksichtigen',
  'optimizeExistingtours': 'Bestandstouren aktualisieren',
  'optimizeSplitTours': 'Tour aufteilen',
  'sprinter_max_kg': 'Sprinter max. Zuladung 1200 kg',
  'caddy_max_kg': 'Caddy max. Zuladung 500 kg',
  'kombi_max_kg': 'Kombi max. Zuladung 350 kg',
  'bike_max_kg': 'Bike max. Zuladung 30 kg',
  'time': 'Zeit',
  'distance': 'Entfernung',
  'optimization': 'Optimierung',
  'optimization-tour': 'Optimierung-Tour',
  'stops': 'Stopps',
  // report report_tourplan
  'report_tourplan': 'Tourenplan',
  'tourID': 'Tour Nr.',
  'optimized': 'optimiert',
  'not_optimized': 'nicht optimiert',
  // pickupdispo
  'info': 'Info',
  'open_orders_max3days': 'Offene Aufträge (max. 3 Tage)',
  'processed_orders_today': 'Disponierte Aufträge (heute)',
  'open_orders': 'offene Aufträge',
  'processed_orders': 'disponierte Aufträge',
  'not_loaded': 'nicht beladen',
  'packs_without_loadingscan_max3days': 'Packstücke ohne Beladescan (max. 3 Tage)',
  'completed_orders_today': 'Erledigte Aufträge (heute)',
  'third_party_pickup': 'Fremd-PU',
  'status_third_party_pickup_max3days': 'Stati Fremd-Pickups (max. 3 Tage)',
  'status': 'Status',
  'own_pickup': 'eigene PU',
  'status_own_pickup_max3days': 'Stati eigene Pickups (max. 3 Tage)',
  'status_overview': 'Statusübersicht',
  'status_overview_max3days': 'Statusübersicht (max. 3 Tage)',
  // state of shipment
  'shipment-No': 'Sendungs-Nr',
  'ad_hoc_accounting': 'ad hoc Abrechnung',
};

