export const LANG_EN_TRANS = {
  // login form
  'login': 'Login',
  'username': 'Username',
  'btlogin': 'login',
  'username is required': 'Username is required',
  'User does not exist': 'User does not exist',
  'User authentication failed': 'User authentication failed',
  'password': 'Password',
  'password is required': 'Password is required',
  // menu
  'home': 'Home',
  'footer': 'Footer',
  'dispo': 'Dispo',
  'tour': 'Tour',
  'management': 'Management',
  'users': 'Users',
  'logout': 'Logout',
  // user form
  'firstname': 'First Name',
  'surname': 'Surname',
  'email': 'Email',
  'phone': 'Phone',
  'alias': 'Alias',
  'role': 'Role',
  'active': 'Active',
  'inactive': 'Inactive',
  // 'FirstnameMinLength': 'Firstname needs to be at least 3 characters long',
  'FirstnameMaxLength': 'Firstname cannot exceed 45 characters',
  // 'SurnameMinLength': 'Surname needs to be at least 3 characters long',
  'SurnameMaxLength': 'Surname cannot exceed 45 characters',
  // 'PwdMinLength': 'Password needs to be at least 5 characters long',
  'PwdMaxLength': 'Password cannot exceed 25 characters',
  // 'EmailMinLength': 'Email needs to be at least 3 characters long',
  // 'EmailMaxLength': 'Email cannot exceed 100 characters',
  'PhoneMaxLength': 'Phone cannot exceed 45 characters',
  // 'AliasMinLength': 'Alias needs to be at least 3 characters long',
  'AliasMaxLength': 'Alias cannot exceed 30 characters',
  'save': 'Save',
  'clear': 'Clear',
  'Admin': 'Admin',
  'Poweruser': 'Poweruser',
  'User': 'User',
  'Driver': 'Driver',
  'Customer': 'Customer',
  'EmailFormat': 'Invalid format of email address',
  'duplicate email': 'Email address already exists.',
  'expires_on': 'Expires on',
  'user account deactivated': 'Your account is deactivated',
  'yes': 'yes',
  'no': 'no',
  'UserInsertSuccessful': 'User insert successful',
  'UserUpdateSuccessful': 'User update successful',
  'apprights': 'App Rights',
  'hub': 'HUB',
  'route': 'Route',
  'station': 'Station',
  // map form
  'allusers': 'all users',
  'drivers': 'drivers',
  'could not get geolocation points': 'Could not get geolocation points',
  'could not get route': 'Could not get route',
  'name': 'Name',
  'vehicle': 'Vehicle',
  'phoneoffice': 'Phone Office',
  'phonemobile': 'Phone Mobile',
  'lastactivity': 'Last activity',
  'bike': 'Bike',
  'car': 'Car',
  'van': 'Van',
  'truck': 'Truck',
  'unknown': 'Unknown',
  'last': 'last',
  'hours': 'hours',
  // stationloading form - loadinglist
  'loadingcontrol': 'Loading control',
  'newloadlist': 'New loadlist',
  'payload': 'Payload in Kg',
  'exportdate': 'Date of export',
  'loadlist': 'loadlist',
  'printlabel': 'label',
  'alllists': 'all lists',
  'selectedlist': 'selected list',
  'actuallist': 'actual list',
  'preview': 'Preview',
  'directprint': 'direct print',
  'information': 'Information',
  'loadlistnumber': 'Loadlist-No',
  'loadedweight': 'loaded (Kg)',
  'freeweight': 'free weight (Kg)',
  'stillopen': 'still open',
  'packcount': 'No of packs',
  'weight': 'Weight',
  'loaded': 'loaded',
  'notloaded': 'open',
  'loadingscan': 'Loadingscan',
  'packages': 'Packages',
  'scanmsgfield': 'Scan Message',
  'scanfield': 'Scanfield',
  'loadinglistscan': 'Loadlistscan',
  'bagscan': 'Bagscan',
  'packageId': 'PackNo',
  'zip': 'Zip',
  'city': 'City',
  'devliveryStation': 'Station of delivery',
  'loadinglistNo': 'Loadinglist No',
  'loadinglist': 'Loadinglist',
  'wrapperType': 'Wrappertype',
  'valore': 'Valore',
  'print': 'Print',
  'noAction': 'No action selected',
  'actionNewLoadlist': 'Action: New loadlist',
  'actionChangePayload': 'Action: Change payload',
  'actionChangeLoadlist': 'Action: Change loadlist',
  'notOnLoadlist': 'not yet on loadlist',
  'onLoadlist': 'already loaded',
  // stationloading form - bagscan
  'openOnBaglist': 'not yet on baglist',
  'bagInformation': 'Bag Information',
  'bagID': 'Bag-ID',
  'backLabel': 'Backlabel',
  'backSeal': 'Backseal',
  'yellow': 'yellow',
  'packNumber': 'Pack Number',
  'messages': 'Messages',
  'llNo': 'LL-No',
  'statistics': 'Statistics',
  'valCount': 'No of Valore',
  'bagWeightKg': 'Bagweight (Kg)',
  'completeProcessingF5': 'Complete Processing (F5)',
  'swapSealF10': 'Swap Seal (F10)',
  'update': 'Update',
  'noLlNoSet': 'No loadlistnumber set',
  'noScan': 'no scan',
  'alreadyScanned': 'bereits gescannt',
  'noAlreadyScanned': 'This shipment no has already been scanned.',
  'transferedToOtherLoadlist': 'This shipmentnumber has already been scanned to another loadlist and will be ' +
  'transfered to the actual one.',
  'noDataInDatabase': 'No data in database for this shipmentnumber.',
  'depotMismatch': 'Scan not possible, since you are not the pickup station for this shipment.',
  'invalidSenddate': ' The date of shipment does not correspond to the specified criteria. ' +
  'Please correct and try again.',
  'invalidProduct': 'This shipment is no <ONS>. Scan not possible. Please correct and try again.',
  'noValoreScan': 'This shipment is a Valore. Scan not possible. Valore must be scanned into a bag.',
  'baglist': 'Baglist',
  'bagCountMsgfield': 'Your bag inventory exceeds your quota.' + '<br>' +
  'Please return 3 bags for relief.',
  'infoMsgfield': 'Open the scanning panel with F2.' + '<br>' +
  'Clear fields with F3.' + '<br>' +
  'Finish processing with F5.' + '<br>' +
  'Replace regular seal with emergency seal with F10.'
};
