export const LANG_EN_TRANS = {
  // login form
  'login': 'Login',
  'username': 'Username',
  'btlogin': 'login',
  'username is required': 'Username is required',
  'User does not exist': 'User does not exist',
  'User authentication failed': 'User authentication failed',
  'password': 'Password',
  'password is required': 'Password is required',
  'loggedinas': 'Logged in as',
  'On login-change you have to provide a password': 'On login-change you have to provide a password',
  // menu
  'home': 'Home',
  'lists': 'Lists',
  'footer': 'Footer',
  'scans': 'Scans',
  'driver-assignment': 'Driver Assignment',
  'driver': 'Driver',
  'forStation': 'for Station',
  'orders': 'orders',
  'recording': 'recording',
  'action dispatch': 'action dispatch',
  'standing orders': 'standing orders',
  'disposition': 'disposition',
  'inbound disposition': 'inbound disposition',
  'tour planning': 'tour planing',
  'tour optimization': 'tour optimization',
  'outbound disposition': 'outbound disposition',
  'reprint stoplist': 'reprint stoplist',
  'scanning': 'scanning',
  'inbound scan': 'inbound scan',
  'outbound scan': 'outbound scan',
  'depot entry': 'depot entry',
  'stoplist scan': 'stopplist scan',
  'track & trace': 'track & trace',
  'shipment information': 'shipment information',
  'vehicle tracing' : 'vehicle tracing',
  'stoplist backinput': 'stoplist backinput',
  'shipment cockpit': 'shipment cockpit',
  'line haul': 'line haul',
  'administration': 'administration',
  'customer administration': 'customer administration',
  'user administration': 'user administration',
  'addresspool': 'addresspool',
  'mobileX': 'mobileX',
  'settings': 'settings',
  'startpage': 'startpage',
  'communication': 'communication',
  'printer administration': 'printer administration',
  'comports': 'comports',
  'interfaces': 'interfaces',
  'addons': 'addons',
  'routing': 'routing',
  'stationfinder': 'stationfinder',
  'datafilter': 'datafilter',
  'print lists': 'print lists',
  'search location': 'search location',
  'export/import data': 'export/import data',
  'request data': 'data requester',
  'statistics': 'statistics',
  'quality': 'quality',
  'logout': 'logout',
  // 'statistics': 'Statistics', (see below)
  'pod-reprints': 'Deliverylist reprint',
  'client-management': 'Client management',
  'client-data': 'Client data',
  'periodic-shipments': 'Periodic shipments',
  'promotion-shipments': 'Promotion shipments',
  'office-management': 'Office management',
  'printer-setup': 'Printer setup',
  'password-management': 'Password management',
  'directinfo-to-partner': 'Directinfo to Partner',
  'supportrequest': 'Supportrequest',
  'notification': 'Notification',
  'accessoires': 'Accessoires',
  'stationlist': 'Stationlist',
  'townsearch': 'Townsearch',
  'dataexport': 'Dataexport',
  'documents': 'Documents',
  'calendar': 'Calendar',
  'tracking': 'Tracking',
  'tour': 'Tour',
  'management': 'Management',
  'co-worker': 'Co-Worker',
  // user form
  'firstname': 'First Name',
  'surname': 'Surname',
  'email': 'Email',
  'emailOrLogin': 'Email/Login',
  'phone': 'Phone',
  'alias': 'Alias',
  'aliasOrDriver': 'Alias/DriverNo',
  'role': 'Role',
  'active': 'Active',
  'inactive': 'Inactive',
  // 'FirstnameMinLength': 'Firstname needs to be at least 3 characters long',
  'FirstnameMaxLength': 'Firstname cannot exceed 45 characters',
  // 'SurnameMinLength': 'Surname needs to be at least 3 characters long',
  'SurnameMaxLength': 'Surname cannot exceed 45 characters',
  'PwdMinLength': 'Password needs to be at least 6 characters long',
  'PwdMaxLength': 'Password cannot exceed 25 characters',
  // 'EmailMinLength': 'Email needs to be at least 3 characters long',
  // 'EmailMaxLength': 'Email cannot exceed 100 characters',
  'PhoneMaxLength': 'Phone cannot exceed 45 characters',
  // 'AliasMinLength': 'Alias needs to be at least 3 characters long',
  'AliasMaxLength': 'Alias cannot exceed 30 characters',
  'save': 'Save',
  'clear': 'Clear',
  'Admin': 'Admin',
  'Poweruser': 'Poweruser',
  'User': 'User',
  'Driver': 'Driver',
  'Customer': 'Customer',
  'EmailFormat': 'Invalid format of email address',
  'duplicate email': 'Email address already exists.',
  'expires_on': 'Expires on',
  'user account deactivated': 'Your account is deactivated',
  'yes': 'yes',
  'no': 'no',
  'UserInsertSuccessful': 'User insert successful',
  'UserUpdateSuccessful': 'User update successful',
  'UserSuccessfulDeactive': 'User successfully deactivated',
  'apprights': 'App Rights',
  'hub': 'HUB',
  'route': 'Route',
  'station': 'Station',
  'line': 'Line',
  'homebase': 'Home',
  'forExample': 'eg:',
  'egMail': 'DriverNo@StationNo',
  // map form
  'allusers': 'all users',
  'drivers': 'drivers',
  'alldrivers': 'all drivers',
  'could not get geolocation points': 'Could not get geolocation points',
  'could not get route': 'Could not get route',
  'name': 'Name',
  'vehicle': 'Vehicle',
  'phoneoffice': 'Phone Office',
  'phonemobile': 'Phone Mobile',
  'lastactivity': 'Last activity',
  'bike': 'Bike',
  'car': 'Car',
  'van': 'Van',
  'truck': 'Truck',
  'unknown': 'Unknown',
  'last': 'Last',
  'hs': 'hours',
  'refreshevery': 'Refresh ervery',
  'mins': 'min',
  'latestRefresh': 'Latest refresh',
  'showlist': 'list fade in/out',
  'selectedformap': 'Selected for Map',
  'day': 'Day',
  // stationloading form - loadinglist
  'loadingcontrol': 'Loading control',
  'newloadlist': 'New loadlist',
  'payload': 'Payload in Kg',
  'exportdate': 'Date of export',
  'loadlist': 'loadlist',
  'printlabel': 'Label',
  'alllists': 'all lists',
  'selectedlist': 'selected list',
  'actuallist': 'actual list',
  'preview': 'Preview',
  'printpreview': 'Print Preview',
  'directprint': 'direct print',
  'information': 'Information',
  'loadlistnumber': 'Loadlist-No',
  'loadedweight': 'loaded (Kg)',
  'freeweight': 'free weight (Kg)',
  'stillopen': 'still open',
  'packcount': 'No of packs',
  'weight': 'Weight',
  'loaded': 'loaded',
  'notloaded': 'open',
  'packages': 'Packages',
  'scanmsgfield': 'Scan Message',
  'scanfield': 'Scanfield',
  'loadinglistscan': 'Loadlistscan',
  'bagscan': 'Bagscan',
  'zip': 'Zip',
  'city': 'City',
  'devliveryStation': 'Station of delivery',
  'loadinglistNo': 'Loadinglist No',
  'loadinglist': 'Loadinglist',
  'wrapperType': 'Wrappertype',
  'valore': 'Valore',
  'print': 'Print',
  'noAction': 'No action selected',
  'actionNewLoadlist': 'Action: New loadlist',
  'actionChangePayload': 'Action: Change payload',
  'actionChangeLoadlist': 'Action: Change loadlist',
  'notOnLoadlist': 'not yet on loadlist',
  'onLoadlist': 'already loaded',
  'noDataAvailable': 'no data available',
  'no activeLoadinglist': 'no loadlist selected',
  // stationloading form - bagscan
  'openOnBaglist': 'not yet on baglist',
  'bagInformation': 'Bag Information',
  'bagID': 'Bag-ID',
  'backLabel': 'Backlabel',
  'backSeal': 'Backseal',
  'yellow': 'yellow',
  'packNumber': 'Pack Number',
  'messages': 'Messages',
  'llNo': 'LL-No',
  'valCount': 'No of Valore',
  'bagWeightKg': 'Bagweight (Kg)',
  'completeProcessingF5': 'Complete Processing (F5)',
  'swapSealF10': 'Swap Seal (F10)',
  'update': 'Update',
  'noLlNoSet': 'No loadlistnumber set',
  'noScan': 'no scan',
  'alreadyScanned': 'bereits gescannt',
  'noAlreadyScanned': 'This shipment no has already been scanned.',
  'transferedToOtherLoadlist': 'This shipmentnumber has already been scanned to another loadlist and will be transfered.',
  'noDataInDatabase': 'No data in database for this shipmentnumber.',
  'depotMismatch': 'Scan not possible, since you are not the pickup station for this shipment.',
  'invalidSenddate': ' The date of shipment does not correspond to the specified criteria. ' +
  'Please correct and try again.',
  'invalidProduct': 'This shipment is no <ONS>. Scan not possible. Please correct and try again.',
  'noValoreScan': 'This shipment is a Valore. Scan not possible. Valore must be scanned into a bag.',
  'baglist': 'Baglist',
  'bagCountMsgfield': 'Your bag inventory exceeds your quota.' + '<br>' +
  'Please return 3 bags for relief.',
  'infoMsgfield': 'Open the scanning panel with F2.' + '<br>' +
  'Clear fields with F3.' + '<br>' +
  'Finish processing with F5.' + '<br>' +
  'Swap to emergency seal with F10.',
  'maxBagWeightReached': 'Maximum bagweight reached',
  'caution': 'Caution',
  'activateBlueSeal': 'Activate the blue seal if you have an important reason',
  'scanBlueSeal': 'Scan Seal (blue)',
  'reason': 'Reason',
  'saveF7': 'Save (F7)',
  'noBagIDSet': 'The field <Bag-ID> may not be empty',
  'noBackLabelSet': 'The field <Backlabel> may not be empty',
  'noBackSealSet': 'The field <Backseal (yellow)> must be empty',
  'noSealActivation': 'You may not activate the emergency seal if you already have a valid seal specified',
  'noBlueSealNoSet': 'The Field <Scan Seal (blue)> may not be empty',
  'noReasonSet': 'The Field <Reason> may not be empty',
  'clearFields': 'Clear fields',
  // reports
  'report_loadinglist': 'Loadinglist',
  'date': 'Date',
  'to_auf': 'to',
  'from': 'from',
  'to_nach': 'to',
  'total_CountShipments': 'Total shipments',
  'total_CountPackages': 'Total packages',
  'total_Weight': 'Total weight',
  'totalPackagesToTransport': 'The following packages were loaded for transport without damage',
  'nameOfDriver': 'Name of driver',
  'licensePlate': 'License plate',
  'loadingDate': 'Date',
  'loadingTime': 'Time',
  'signature': 'Signature',
  'llDriver': '(Contractor/Driver)',
  'page': 'Page',
  'printingDate': 'Printingdate',
  // importscan form - importscan quick - importscan check
  'newShipment': 'New Shipment',
  'allShipments': 'All Shipments',
  'controlscan': 'Controlscan',
  'listprinting': 'Print Lists',
  'sortorder': 'Sorting',
  'standard': 'Standard',
  'importlist': 'Importlist',
  'quickscan': 'Quickscan',
  'refresh': 'Refresh',
  'to': 'to',
  'typeOfPackaging': 'Type of Packaging',
  'parcelno': 'Parcel No',
  'packs': 'Parcels',
  'vol-Weight': 'Vol Weight',
  'real-Weight': 'Real Weight',
  'length': 'Length',
  'width': 'Width',
  'height': 'Height',
  'import_controllist': 'Import Controllist',
  // deliveryscan form
  'deliverylistscan': 'Deliverylist scan',
  'tourno': 'Tour No',
  'deliverydate': 'Deliverydate',
  'help': 'Help',
  'newDeliverylist': 'new Deliverylist',
  'deliverylistno': 'Deliverylist No',
  'sortZip': 'by Zip',
  'sortDeadline': 'by Deadline',
  'withImportScan': 'with Importscan',
  'justforDeliverydate': 'just for Deliverydate',
  'justActualTour': 'just actual Tour',
  'tourNo': 'Tour No',
  'deliverylistNo': 'Deliverylist No',
  'shipmentCount': 'No of Shipments',
  'packageCount': 'No of Packs',
  'afternoon': 'Afternoon',
  'free': 'Free',
  'realWeight': 'Real Weight',
  'volumeWeight': 'Volume Weight',
  'effectiveWeight': 'Effective Weight',
  'sorting': 'Sorting',
  // deliveryscan list, delivery dispo
  'pos': 'Pos',
  'consignee': 'Consignee',
  'deadline': 'Deadline',
  'shipmentno': 'Ship No',
  'deliverystatus': 'Status',
  'deliverycode': 'Code',
  'shipment': 'Shipments',
  'count': 'Count',
  'expected': 'to expect',
  'throughHub': 'through HUB',
  'onTruck': 'on truck',
  'withImportscan': 'with importscan',
  'filter': 'Filter',
  'uptoDeliverydate': 'up to deliverydate',
  'forDeliverydate': 'for deliverydate',
  'withStock': 'on stock',
  'select': 'Select',
  'hidePU': 'hide PickUps',
  'glsDelivery': 'GLS delivery',
  'allTours': 'all Tours',
  'justForTour': 'just for Tour',
  'predispo': 'pre Dispo',
  'detailedDispo': 'detailed Dispo',
  'street': 'Street',
  'vol.': 'Vol.',
  'shipmentNo': 'Shipment No',
  'tourdispo': 'Tourdispo',
  'tourinfo': 'Tourinfo',
  'rk': 'RK',
  'tour-deliverydispo': 'Tour/Delivery Dispo',
  'deliveryinfo': 'Delivery Info',
  // ipointlist, ipointquick
  'scan_without_validating': 'Scan without validating',
  'ipointlist': 'I-Point List',
  'ipoint_quickscan': 'I-Point quickscan',
  'total_real_Weight': 'Total real weight',
  'total_vol_Weight': 'Total vol weight',
  'ipointListcan': 'I-Point listscan',
  'packages_to_scan': 'Packages to scan',
  // tourzipmapping
  'tourzipmapping': 'Tour/Zip mapping',
  'driverNo': 'Driver No',
  'drivername': 'Drivername',
  'fromZip': 'from Zip',
  'toZip': 'to Zip',
  'setnewArea': 'set new area',
  // orderform
  'consignor': 'Consignor',
  'client': 'Client',
  'consignorClientNos': 'Sender No (F11)',
  'consigneeClientNos': 'Delivery No (F12)',
  'consignorClientReNos': 'Client No Inv.',
  'customer': 'Customer',
  'reference': 'Reference',
  'pickup': 'Pickup',
  'senderLine1': 'Sender Line 1',
  'senderLine2': 'Sender Line 2',
  'senderLine3': 'Sender Line 3',
  'pickupTimeWindow': 'Hours',
  'serviceF7': 'Service (F7)',
  'serviceF8': 'Service (F8)',
  'pickupInfo': 'Info',
  'pickupContact': 'Contact',
  'clientInvoice': 'Client Inv (F4)',
  'delivery': 'Delivery',
  'deliveryLine1': 'Delivery Line 1',
  'deliveryLine2': 'Delivery Line 2',
  'deliveryLine3': 'Delivery Line 3',
  'deliveryTimeWindow': 'Hours',
  'deliveryInfo': 'Info',
  'deliveryContact': 'Contact',
  'system': 'System',
  'orderform': 'Orderform',
  'orderlist': 'Orderlist',
  'CC': 'CC',
  'No': 'No',
  'orderingParty': 'Ordering Party',
  'collector': 'Collector',
  'deliverystation': 'Deliverystation',
  'pickupdate': 'Pickupdate',
  'until': 'to',
  'fixPickup': 'Fix Pickup',
  'realweight': 'Real weight',
  'volweight': 'Volume weight',
  'payweight': 'Payweight',
  'exportcosts': 'Exportcosts (PU)',
  'description': 'Description',
  'productvalue': 'Productvalue',
  'liabilityvalue': 'Liabilityvalue',
  'insurance': 'Insurance',
  'total': 'Total',
  'pickupInfoDispo': 'Pickupinfo dispo',
  'XChRetNo': 'X-Change Ret.No',
  'accountingClient': 'Accounting client',
  'fixDelivery': 'Fix Delivery',
  'importcosts': 'Importcosts',
  'content': 'Content',
  'cod': 'COD',
  'infoDeliverylist': 'Info Deliverylist',
  'deliveryInfoDispo': 'Deliveryinfo dispo',
  'shipmentF3': 'Shipment (F3)',
  'package-No': 'Package-No',
  'productSpecification': 'Product specification',
  'products': 'Products',
  'distanceDirectKM': 'Distance (Direct)',
  'ad_hoc_CostsF5': 'ad hoc Costs (F5)',
  'verify': 'Verify',
  'saveF2': 'Save (F2)',
  'newStrgN': 'New (Strg+N)',
  'delete': 'Delete',
  'printF9': 'Print (F9)',
  'label': 'Label',
  'waybill': 'Waybill',
  'PickUp': 'Pick Up',
  // orderlist
  'senddate': 'Senddate',
  'avisnumber': 'Avisnumber',
  'shipmentoverview_max_10_days': 'Shipmentoverview (max. 10 days)',
  // statusbar
  'not_connected_to_leoz': 'not connected to leoz',
  'connected_to_leoz': 'connected to leoz',
  // touroptimizing
  'touroptimizing': 'Tour optimizing',
  'stoplist': 'Stoplist',
  'deliverylists': 'Deliverylists',
  'tourlists': 'Tourlists',
  'mark_all_none': 'Mark all/none',
  'none': 'None',
  'all': 'All',
  'optimize': 'Optimize',
  'driverlists': 'Driverlists',
  'tours-most-likely-outdated': 'There has been a change in your deliverylists. ' +
                                'To make sure you are up to date, you should press "reset"',
  'optimization_progress': 'Optimization in progress...',
  'optimizing_optimized_tours_not_possible': 'Optimizing optimized tours not possible',
  'optimizationOptions': 'Optimization options',
  'cancel': 'Cancel',
  'start': 'Start',
  'no_optimizable_tours_selected': 'No optimizable tours selected',
  'optimizeTodayAndFuture': 'Tourstart today',
  'optimizeTraffic': 'Consider traffic',
  'optimizeExistingtours': 'Optimize existing tours',
  'optimizeSplitTours': 'Split tours',
  'sprinter_max_kg': 'Sprinter max. payload 1200 kg',
  'caddy_max_kg': 'Caddy max. payload 500 kg',
  'kombi_max_kg': 'Kombi max. payload 350 kg',
  'bike_max_kg': 'Bike max. payload 30 kg',
  'time': 'Time',
  'distance': 'Distance',
  'optimization': 'Optimization',
  'optimization-tour': 'Optimization-Tour',
  'stops': 'Stops',
  // report report_tourplan
  'report_tourplan': 'Tour Plan',
  'tourID': 'Tour No.',
  'optimized': 'optimized',
  'not_optimized': 'not optimized',
  // pickupdispo
  'info': 'Info',
  'open_orders_max3days': 'Open Orders (max. 3 days)',
  'processed_orders_today': 'Processed Orders (today)',
  'open_orders': 'open orders',
  'processed_orders': 'processed orders',
  'not_loaded': 'not loaded',
  'packs_without_loadingscan_max3days': 'Packs without loadingscan (max. 3 days)',
  'completed_orders_today': 'Completed Orders (today)',
  'third_party_pickup': 'Third Party Pickups',
  'status_third_party_pickup_max3days': 'Status Third Party Pickups (max. 3 days)',
  'status': 'Status',
  'own_pickup': 'own pickup',
  'status_own_pickup_max3days': 'Status own Pickups (max. 3 days)',
  'status_overview': 'Status overview',
  'status_overview_max3days': 'Status overview (max. 3 days)',
  // state of shipment
  'shipment-No': 'Shipment-No',
  'ad_hoc_accounting': 'ad hoc accounting',
};







