export const LANG_DE_TRANS = {
  // login form
  'login': 'Anmeldung',
  'username': 'Benutzername',
  'btlogin': 'anmelden',
  'username is required': 'Benutzername muss angegeben werden',
  'User does not exist': 'Benutzername existiert nicht',
  'User authentication failed': 'Anmeldung fehlgeschlagen',
  'password': 'Kennwort',
  'password is required': 'Kennwort muss angegeben werden',
  'loggedinas': 'Angemeldet als',
  // menu
  'home': 'Startseite',
  'footer': 'Fussbereich',
  'dispo': 'Disposition',
  'tour': 'Tour',
  'management': 'Management',
  'users': 'Mitarbeiter',
  'logout': 'Abmelden',
  // user form
  'firstname': 'Vorname',
  'surname': 'Nachname',
  'email': 'Email',
  'emailOrLogin': 'Email/Login',
  'phone': 'Telefon',
  'alias': 'Alias',
  'aliasOrDriver': 'Alias/FahrerNr',
  'role': 'Rolle',
  'active': 'Aktiv',
  'inactive': 'nicht aktiv',
  // 'FirstnameMinLength': 'Der Vorname muss aus mindestens 3 Zeichen bestehen',
  'FirstnameMaxLength': 'Der Vorname darf maximal 45 Zeichen lang sein',
  // 'SurnameMinLength': 'Der Nachname muss aus mindestens 3 Zeichen bestehen',
  'SurnameMaxLength': 'Der Nachname darf maximal 45 Zeichen lang sein',
  'PwdMinLength': 'Das Kennwort muss aus mindestens 6 Zeichen bestehen',
  'PwdMaxLength': 'Das Kennwort darf nicht mehr als 25 Zeichen haben',
  // 'EmailMinLength': 'Die Emailadresse muss aus mindestens 3 Zeichen bestehen',
  // 'EmailMaxLength': 'Die Emailadresse darf nicht mehr als 100 Zeichen haben',
  'PhoneMaxLength': 'Die Telefonnummer darf nicht mehr als 45 Zeichen haben',
  // 'AliasMinLength': 'Alias muss aus mindestens 3 Zeichen bestehen',
  'AliasMaxLength': 'Alias darf maximal 30 Zeichen lang sein',
  'save': 'Speichern',
  'clear': 'Leeren',
  'Admin': 'Admin',
  'Poweruser': 'Extrem-Benutzer',
  'User': 'Benutzer',
  'Driver': 'Fahrer',
  'Customer': 'Kunde',
  'EmailFormat': 'Kein korrektes Format der E-Mailadresse',
  'duplicate email': 'Die E-Mailadresse existiert bereits.',
  'expires_on': 'Gültig bis',
  'user account deactivated': 'Ihr Konto ist deaktiviert',
  'yes': 'ja',
  'no': 'nein',
  'UserInsertSuccessful': 'Benutzer erfolgreich angelegt',
  'UserUpdateSuccessful': 'Benutzer erfolgreich geändert',
  'UserSuccessfulDeactive': 'Benutzer erfolgreich deaktiviert',
  'apprights': 'App Berechtigungen',
  'hub': 'HUB',
  'route': 'Linie',
  'station': 'Station',
  'line': 'Line',
  'homebase': 'Home',
  'forExample': 'z.B.:',
  'egMail': 'FahrerNr@StationNr',
  // map form
  'allusers': 'alle Mitarbeiter',
  'drivers': 'Fahrer',
  'alldrivers': 'alle Fahrer',
  'could not get geolocation points': 'Keine Geokoordinaten gefunden',
  'could not get route': 'Keine Route gefunden',
  'name': 'Name',
  'vehicle': 'Fahrzeug',
  'phoneoffice': 'Telefon Büro',
  'phonemobile': 'Telefon Mobil',
  'lastactivity': 'letzte Aktivität',
  'bike': 'Fahrrad',
  'car': 'PKW',
  'van': 'Bus',
  'truck': 'LKW',
  'unknown': 'unbekannt',
  'last': 'Letzte',
  'hs': 'Std',
  'refreshevery': 'Aktualisieren alle',
  'mins': 'Min',
  'latestRefresh': 'Zuletzt aktualisiert',
  'showlist': 'Liste ein-/ausblenden',
  'selectedformap': 'Ausgewählt für Karte',
  'day': 'Tag',
  // stationloading form - loadinglist
  'loadingcontrol': 'Verladesteuerung',
  'newloadlist': 'Neue Ladeliste',
  'payload': 'Zuladung in Kg',
  'exportdate': 'Versanddatum',
  'loadlist': 'Ladeliste',
  'printlabel': 'Label',
  'alllists': 'alle',
  'selectedlist': 'für Auswahl',
  'actuallist': 'aktuell',
  'preview': 'Vorschau',
  'directprint': 'Sofortdruck',
  'information': 'Information',
  'loadlistnumber': 'Ladelisten Nr',
  'loadedweight': 'geladene (Kg)',
  'freeweight': 'noch frei (Kg)',
  'stillopen': 'noch offen',
  'packcount': 'Anzahl PkSt',
  'weight': 'Gewicht',
  'loaded': 'geladen',
  'notloaded': 'offen',
  'loadingscan': 'Ladelistenscan',
  'packages': 'Packstücke',
  'scanmsgfield': 'Scan Nachrichten',
  'scanfield': 'Scanfeld',
  'loadinglistscan': 'Ladelistenscan',
  'bagscan': 'Bagscan',
  'packageId': 'PkSt Nr',
  'zip': 'PLZ',
  'city': 'Ort',
  'devliveryStation': 'Lieferdepot',
  'loadinglistNo': 'Ladelisten Nr',
  'loadinglist': 'Ladeliste',
  'wrapperType': 'Verpackungsart',
  'valore': 'Valore',
  'print': 'Drucken',
  'noAction': 'keine Aktion ausgewählt',
  'actionNewLoadlist': 'Aktion: Neue Ladeliste',
  'actionChangePayload': 'Aktion: Änderung der Zuladung',
  'actionChangeLoadlist': 'Aktion: Wechsel Ladeliste',
  'notOnLoadlist': 'noch nicht auf Ladeliste',
  'onLoadlist': 'bereits geladen',
  'noDataAvailable': 'keine Einträge vorhanden',
  // stationloading form - bagscan
  'openOnBaglist': 'noch nicht auf Bagliste',
  'bagInformation': 'Bag Information',
  'bagID': 'Bag-ID',
  'backLabel': 'Rücklabel',
  'backSeal': 'Rückplombe',
  'yellow': 'gelb',
  'packNumber': 'Packstücknummer',
  'messages': 'Meldungen',
  'llNo': 'LL-Nr',
  'statistics': 'Statistiken',
  'valCount': 'Anzahl Valoren',
  'bagWeightKg': 'Baggewicht (Kg)',
  'completeProcessingF5': 'Bearbeitung abschliessen (F5)',
  'swapSealF10': 'Tausch auf Notfallplombe (F10)',
  'update': 'Aktualisieren',
  'noLlNoSet': 'Keine Ladelistennummer gesetzt',
  'noScan': 'kein Scan',
  'alreadyScanned': 'bereits gescannt',
  'noAlreadyScanned': 'Diese Belegnummer wurde bereits gescannt.',
  'transferedToOtherLoadlist': 'Diese Belegnummer wurde bereits auf eine andere Ladeliste gescannt und wird jetzt umgebucht.',
  'noDataInDatabase': 'Kein Datensatz vorhanden.',
  'depotMismatch': 'Nicht scanbar, da Sie für diese Sendung nicht das abholende Depot sind.',
  'invalidSenddate': 'Das Verladedatum der Sendung entspricht nicht den vorgegebenen Kriterien. ' +
  'Bitte in der Auftragserfassung nachbearbeiten.',
  'invalidProduct': 'Diese Sendung ist kein <ONS>. Scan nicht möglich. Bitte in der Auftragserfassung nachbearbeiten.',
  'noValoreScan': 'Dieses Packstück ist eine Valore. Scan nicht möglich. Valoren müssen in einen Bag gescannt werden.',
  'baglist': 'Bagliste',
  'bagCountMsgfield': 'Ihr Bag-Bestand überschreitet Ihr Kontingent.' + '<br>' +
                      'Bitte senden Sie zur Entlastung 3 Bags zurück.',
  'infoMsgfield': 'Belegscanfeld öffnen mit F2.' + '<br>' +
                      'Felder leeren mit F3.' + '<br>' +
                      'Bearbeitung abschliessen mit F5.' + '<br>' +
                      'Tausch auf Notfallplombe mit F10.',
  'maxBagWeightReached': 'Maximalgewicht erreicht',
  'caution': 'Achtung',
  'activateBlueSeal': 'Aktivieren der blauen Plombe, wenn Sie einen wichtigen Grund haben',
  'scanBlueSeal': 'Scan Notfallplombe (blau)',
  'reason': 'Grund',
  'saveF7': 'Speichern (F7)',
  'noBagIDSet': 'Das Feld <Bag-ID> darf nicht leer sein',
  'noBackLabelSet': 'Das Feld <Rücklabel> darf nicht leer sein',
  'noBackSealSet': 'Das Feld <Rückplombe (gelb)> muss leer sein',
  'noSealActivation': 'Sie können keine Notfallplombe aktivieren, wenn Sie bereits eine gültige Rückplombe angegeben haben.',
  'noBlueSealNoSet': 'Das Feld <Scan Notfallplombe (blau)> darf nicht leer sein',
  'noReasonSet': 'Das Feld < Grund > darf nicht leer sein',
  'clearFields': 'Felder leeren',
  // reports
  'report_loadinglist': 'Ladeliste',
  'date': 'Datum',
  'to_auf': 'auf',
  'from': 'von',
  'to_nach': 'nach',
  'total_CountShipments': 'Gesamtanzahl Sendungen',
  'total_CountPackages': 'Gesamtanzahl Packstücke',
  'total_Weight': 'Gesamtgewicht',
  'totalPackagesToTransport': 'Folgende Packstücke wurden zum Transport unbeschädigt übernommen',
  'nameOfDriver': 'Name des Fahrers',
  'licensePlate': 'KFZ-Kennzeichen',
  'loadingDate': 'Datum',
  'loadingTime': 'Uhrzeit',
  'signature': 'Unterschrift',
  'llDriver': '(Unternehmer/Fahrer)',
  'page': 'Seite',
  'printingDate': 'Druckdatum',
};

