use dekuclient;

CREATE TABLE `tblauftrag_trx` (
  `OrderID` double NOT NULL DEFAULT '0',
  `AuftragsID` varchar(25) DEFAULT NULL,
  `GKNr` int(11) DEFAULT NULL,
  `Belegnummer` double DEFAULT NULL,
  `DepotNrED` int(11) DEFAULT NULL,
  `DepotNrAbD` int(11) DEFAULT NULL,
  `DepotNrbev` int(11) DEFAULT NULL,
  `DepotNrAD` int(11) DEFAULT NULL,
  `DepotNrZD` int(11) DEFAULT NULL,
  `DepotNrLD` int(11) DEFAULT NULL,
  `lockflag` smallint(6) NOT NULL DEFAULT '1',
  `dtCreateAD` datetime DEFAULT NULL,
  `dtSendAD2Z` datetime DEFAULT NULL,
  `dtReceiveZ2ZD` datetime DEFAULT NULL,
  `dtModifyZD` datetime DEFAULT NULL,
  `dtTermin_von` datetime DEFAULT NULL,
  `dtTermin` datetime DEFAULT NULL,
  `dtAuslieferung` datetime DEFAULT NULL,
  `dtAuslieferDatum` datetime DEFAULT NULL,
  `dtAuslieferZeit` datetime DEFAULT NULL,
  `Empfaenger` varchar(35) DEFAULT NULL,
  `Timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `KDNR` int(9) DEFAULT NULL,
  `FirmaS` varchar(50) DEFAULT NULL,
  `FirmaS2` varchar(50) DEFAULT NULL,
  `LandS` char(3) DEFAULT NULL,
  `PLZS` varchar(10) DEFAULT NULL,
  `OrtS` varchar(50) DEFAULT NULL,
  `StrasseS` varchar(50) DEFAULT NULL,
  `StrNrS` varchar(10) DEFAULT NULL,
  `TelefonVWS` varchar(20) DEFAULT NULL,
  `TelefonNrS` varchar(20) DEFAULT NULL,
  `TelefaxNrS` varchar(20) DEFAULT NULL,
  `FirmaD` varchar(50) DEFAULT NULL,
  `FirmaD2` varchar(50) DEFAULT NULL,
  `LandD` char(3) DEFAULT NULL,
  `PLZD` varchar(10) DEFAULT NULL,
  `OrtD` varchar(50) DEFAULT NULL,
  `StrasseD` varchar(50) DEFAULT NULL,
  `StrNrD` varchar(10) DEFAULT NULL,
  `TelefonVWD` varchar(20) DEFAULT NULL,
  `TelefonNrD` varchar(20) DEFAULT NULL,
  `TelefaxNrD` varchar(20) DEFAULT NULL,
  `GewichtGesamt` double DEFAULT NULL,
  `ColliesGesamt` smallint(6) DEFAULT NULL,
  `PreisNN` double(20,2) NOT NULL DEFAULT '0.00',
  `DatumNN` date DEFAULT NULL,
  `erhaltenNN` int(11) DEFAULT NULL,
  `Feiertag_1` varchar(15) DEFAULT NULL,
  `FeiertagShlD` int(11) DEFAULT NULL,
  `FeiertagShlS` int(11) DEFAULT NULL,
  `Feiertag_2` varchar(15) DEFAULT NULL,
  `ClearingDate` date DEFAULT NULL,
  `ClearingDateMaster` datetime DEFAULT NULL,
  `Satzart` char(1) DEFAULT NULL,
  `Referenz` varchar(30) DEFAULT NULL,
  `Referenz2` varchar(15) DEFAULT NULL,
  `Adr_Nr_Absender` varchar(20) DEFAULT NULL,
  `Adr_Nr_Empfaenger` varchar(20) DEFAULT NULL,
  `Wert` double(8,2) unsigned zerofill DEFAULT NULL,
  `Nachnahmebetrag` double DEFAULT NULL,
  `Versicherungswert` double(10,2) unsigned zerofill DEFAULT NULL,
  `Verladedatum` datetime DEFAULT NULL,
  `Lieferdatum` datetime DEFAULT NULL,
  `Lieferzeit_von` datetime DEFAULT NULL,
  `Lieferzeit_bis` datetime DEFAULT NULL,
  `KZ_Fahrzeug` tinyint(2) unsigned zerofill DEFAULT NULL,
  `KZ_Transportart` tinyint(2) unsigned zerofill DEFAULT NULL,
  `Service` int(10) unsigned zerofill NOT NULL DEFAULT '0000000000',
  `Sendungsstatus` tinyint(4) unsigned zerofill DEFAULT NULL,
  `KZ_erweitert` int(10) unsigned DEFAULT NULL,
  `Information1` varchar(80) DEFAULT NULL,
  `Information2` varchar(40) DEFAULT NULL,
  `Inhalt` varchar(50) DEFAULT NULL,
  `Frei4` varchar(20) DEFAULT NULL,
  `Frei5` varchar(40) DEFAULT NULL,
  `Verladezeit_von` datetime DEFAULT NULL,
  `Verladezeit_bis` datetime DEFAULT NULL,
  `Besteller_Name` varchar(25) DEFAULT NULL,
  `Ladelisten_Nummer` int(8) unsigned zerofill DEFAULT NULL,
  `CR` char(2) DEFAULT NULL,
  `FahrerNr` int(11) DEFAULT NULL,
  `d` int(1) DEFAULT NULL,
  `Info_Rollkarte` longtext,
  `Info_Intern` longtext,
  `termin_i` int(1) unsigned zerofill DEFAULT NULL,
  `Zone` char(1) DEFAULT NULL,
  `Insel` char(1) DEFAULT NULL,
  `Zonea` char(1) DEFAULT NULL,
  `Insela` char(1) DEFAULT NULL,
  `69_Betrag_Abrechnung_Kunde` double(8,2) unsigned zerofill DEFAULT NULL,
  `69_KostenBahnFlug` double(5,2) unsigned zerofill DEFAULT NULL,
  `69_KmDirekt` int(4) unsigned zerofill DEFAULT NULL,
  `69_KZ_SameDay` tinyint(1) unsigned zerofill DEFAULT NULL,
  `Betrag_Importkosten` double(8,2) DEFAULT NULL,
  `Betrag_Importkosten_best` double(8,2) DEFAULT NULL,
  `Betrag_Exportkosten` double(8,2) DEFAULT NULL,
  `Betrag_Exportkosten_best` double(8,2) DEFAULT NULL,
  `Sondervereinbarung` varchar(20) DEFAULT NULL,
  `Importkosten` varchar(20) DEFAULT NULL,
  `ExportkostenPU` varchar(20) DEFAULT NULL,
  `RechnungsNr` varchar(20) DEFAULT NULL,
  `OrtDX` varchar(50) DEFAULT NULL,
  `frueheste_zustellzeit` varchar(4) DEFAULT NULL,
  `UploadStatus` tinyint(4) NOT NULL DEFAULT '0',
  `SendStatus` tinyint(4) NOT NULL DEFAULT '0',
  `SdgArt` varchar(4) DEFAULT NULL,
  `IDSdgArt` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RueckDate` datetime DEFAULT NULL,
  `ClearingArtMaster` int(10) unsigned DEFAULT '0',
  `ZoneS` char(1) DEFAULT NULL,
  `Locking` int(11) DEFAULT NULL,
  `SdgType` char(1) DEFAULT NULL,
  `SdgStatus` char(1) DEFAULT NULL,
  `ROrderID` double DEFAULT NULL,
  `EBOrderID` double DEFAULT NULL,
  `EXAuftragsIDRef` varchar(25) DEFAULT NULL,
  `FirmaS3` varchar(50) DEFAULT NULL,
  `FirmaD3` varchar(50) DEFAULT NULL,
  `product_spec` varchar(5) DEFAULT NULL,
  `BagBelegNrA` double DEFAULT NULL,
  `BagIDNrA` double DEFAULT NULL,
  `PlombenNrA` double DEFAULT NULL,
  `GLSKdnr` double NOT NULL DEFAULT '0',
  `xc_ex_orderid` varchar(60) DEFAULT NULL,
  `AbrechnungKunde` varchar(20) DEFAULT NULL,
  `EmpfName` varchar(40) DEFAULT NULL,
  `BetragAbrechnungKunde` double unsigned zerofill DEFAULT NULL,
  `KostenBahnFlug` double unsigned zerofill DEFAULT NULL,
  `KmDirekt` int(4) unsigned zerofill DEFAULT NULL,
  `KZSameday` tinyint(1) unsigned zerofill DEFAULT NULL,
  `disponiert` int(1) DEFAULT NULL,
  PRIMARY KEY (`OrderID`),
  UNIQUE KEY `DepotNrED` (`DepotNrED`,`DepotNrAD`,`DepotNrZD`,`DepotNrLD`,`OrderID`),
  UNIQUE KEY `DepotNrLD` (`DepotNrLD`,`DepotNrZD`,`DepotNrAD`,`DepotNrED`,`OrderID`),
  KEY `Belegnummer` (`Belegnummer`),
  KEY `AuftragsID` (`AuftragsID`),
  KEY `dtAuslieferung` (`dtAuslieferung`),
  KEY `DepotNrZD` (`DepotNrZD`),
  KEY `Empfaenger` (`Empfaenger`),
  KEY `DepotNrLDx` (`DepotNrLD`),
  KEY `DepotNrAD` (`DepotNrAD`),
  KEY `DepotNrAbD` (`DepotNrAbD`),
  KEY `plzd` (`PLZD`),
  KEY `OrtD` (`OrtD`),
  KEY `DepotNrEDInd` (`DepotNrED`),
  KEY `dtCreateAD` (`dtCreateAD`),
  KEY `FirmaS` (`FirmaS`),
  KEY `SendStatus` (`SendStatus`),
  KEY `Referenz` (`Referenz`),
  KEY `lockflag` (`lockflag`),
  KEY `Verladedatum` (`Verladedatum`),
  KEY `Timestamp` (`Timestamp`),
  KEY `ROrderID` (`ROrderID`),
  KEY `EBOrderID` (`EBOrderID`),
  KEY `EXAuftragsIDRef` (`EXAuftragsIDRef`),
  KEY `Referenz2` (`Referenz2`),
  KEY `BagIDNrA` (`BagIDNrA`),
  KEY `preisNN` (`PreisNN`),
  KEY `service` (`Service`),
  KEY `sdgstatus` (`SdgStatus`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `tblauftragcollies_trx` (
  `OrderID` double NOT NULL DEFAULT '0',
  `OrderPos` smallint(6) NOT NULL AUTO_INCREMENT,
  `CollieBelegNr` double NOT NULL DEFAULT '0',
  `Laenge` smallint(6) NOT NULL DEFAULT '0',
  `Breite` smallint(6) NOT NULL DEFAULT '0',
  `Hoehe` smallint(6) NOT NULL DEFAULT '0',
  `GewichtReal` double NOT NULL DEFAULT '0',
  `GewichtLBH` double NOT NULL DEFAULT '0',
  `GewichtEffektiv` double NOT NULL DEFAULT '0',
  `VerpackungsArt` int(11) NOT NULL DEFAULT '0',
  `Timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Bemerkung` varchar(255) DEFAULT '',
  `Sendungsnummer` varchar(11) NOT NULL DEFAULT '',
  `Laufende_Nummer` tinyint(2) DEFAULT NULL,
  `Frei4` double DEFAULT NULL,
  `i_scan` int(1) DEFAULT NULL,
  `Rollkartennummer` varchar(20) DEFAULT NULL,
  `TourNr2` int(11) DEFAULT NULL,
  `dtEingang2` datetime DEFAULT NULL,
  `dtEingangDepot2` datetime DEFAULT NULL,
  `dtAusgangDepot2` datetime DEFAULT NULL,
  `ueD2H2` int(1) DEFAULT NULL,
  `nueD2H2` int(1) DEFAULT NULL,
  `ueH2D2` int(1) DEFAULT NULL,
  `nueH2D2` int(1) DEFAULT NULL,
  `mydepotid2` int(11) DEFAULT NULL,
  `Timestamp22` datetime DEFAULT NULL,
  `AuslieferDatum2` datetime DEFAULT NULL,
  `AuslieferZeit2` datetime DEFAULT NULL,
  `Empfaenger2` varchar(35) DEFAULT NULL,
  `Verladelinie` double DEFAULT NULL,
  `dtEingangHup3` datetime DEFAULT NULL,
  `dtAusgangHup3` datetime DEFAULT NULL,
  `rKM` double DEFAULT NULL,
  `rkLR` double DEFAULT NULL,
  `RollkartennummerD` double DEFAULT NULL,
  `dtLagereingang` datetime DEFAULT NULL,
  `Beladelinie` double DEFAULT NULL,
  `LadelistennummerD` double DEFAULT NULL,
  `bmpFileName` varchar(100) DEFAULT NULL,
  `mydepotabd` int(11) DEFAULT NULL,
  `cReferenz` varchar(30) DEFAULT NULL,
  `RUP` varchar(3) DEFAULT NULL,
  `RUP_org` varchar(3) DEFAULT NULL,
  `BagBelegNrC` double DEFAULT NULL,
  `BagIDNrC` double DEFAULT NULL,
  `PlombenNrC` double DEFAULT NULL,
  `BagBelegNrAbC` double DEFAULT NULL,
  `val_adr` varchar(35) DEFAULT NULL,
  `lieferstatus` smallint(6) NOT NULL DEFAULT '0',
  `lieferfehler` smallint(6) NOT NULL DEFAULT '0',
  `erstlieferstatus` smallint(6) NOT NULL DEFAULT '0',
  `rollkartendat` datetime DEFAULT NULL,
  `erstlieferfehler` smallint(6) NOT NULL DEFAULT '0',
  `rkposition` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`OrderID`,`OrderPos`),
  KEY `CollieBelegNr` (`CollieBelegNr`),
  KEY `rollkartennummer` (`Rollkartennummer`),
  KEY `iscan` (`i_scan`),
  KEY `OrderID` (`OrderID`),
  KEY `OrderPos` (`OrderPos`),
  KEY `Timestamp` (`Timestamp`),
  KEY `TourNr` (`TourNr2`),
  KEY `dtEingangDepot` (`dtEingangDepot2`),
  KEY `dtAusgangDepot` (`dtAusgangDepot2`),
  KEY `mydepotid` (`mydepotid2`),
  KEY `Timestamp2` (`Timestamp22`),
  KEY `Verladelinie` (`Verladelinie`),
  KEY `dtEingangHup3` (`dtEingangHup3`),
  KEY `dtAusgangHup3` (`dtAusgangHup3`),
  KEY `Frei4` (`Frei4`),
  KEY `RollkartennummerD` (`RollkartennummerD`),
  KEY `Beladelinie` (`Beladelinie`),
  KEY `LadelistennummerD` (`LadelistennummerD`),
  KEY `mydepotabd` (`mydepotabd`),
  KEY `cReferenz` (`cReferenz`),
  KEY `BagIDNrC` (`BagIDNrC`),
  KEY `BagBelegNrC` (`BagBelegNrC`),
  KEY `BagBelegNrAbC` (`BagBelegNrAbC`),
  KEY `VerpackungsArt` (`VerpackungsArt`),
  KEY `ertlieferstatus` (`erstlieferstatus`),
  KEY `lieferstatus` (`lieferstatus`),
  KEY `lieferfehler` (`lieferfehler`),
  KEY `rkposition` (`rkposition`)
) ENGINE=InnoDB AUTO_INCREMENT=76 DEFAULT CHARSET=latin1;
