CREATE TABLE station (
  station_nr       INTEGER   NOT NULL,
  address1         VARCHAR,
  address2         VARCHAR,
  billing_address1 VARCHAR,
  billing_address2 VARCHAR,
  billing_city     VARCHAR,
  billing_country  VARCHAR,
  billing_house_nr VARCHAR,
  billing_street   VARCHAR,
  billing_zip      VARCHAR,
  city             VARCHAR,
  contact_person1  VARCHAR,
  contact_person2  VARCHAR,
  country          VARCHAR,
  email            VARCHAR,
  house_nr         VARCHAR,
  mobile           VARCHAR,
  phone1           VARCHAR,
  phone2           VARCHAR,
  pos_lat          DOUBLE,
  pos_long         DOUBLE,
  sector           VARCHAR,
  service_phone1   VARCHAR,
  service_phone2   VARCHAR,
  strang           INTEGER,
  street           VARCHAR,
  telefax          VARCHAR,
  ustid            VARCHAR,
  web_address      VARCHAR,
  zip              VARCHAR,
  'timestamp'      TIMESTAMP NOT NULL,
  sync_id          BIGINT    NOT NULL,
  PRIMARY KEY (station_nr)
);

CREATE TABLE user (
  email         VARCHAR NOT NULL,
  password      VARCHAR NOT NULL,
  api_key       VARCHAR NOT NULL,
  PRIMARY KEY (email)
);