use dekuclient;

CREATE TABLE `tblstatus_xml` (
  `KZ_Statuserzeuger` char(1) NOT NULL DEFAULT 'E',
  `Packstuecknummer` double unsigned zerofill NOT NULL DEFAULT '0000000000000000000000',
  `Datum` char(8) NOT NULL DEFAULT '',
  `Zeit` char(8) NOT NULL DEFAULT '',
  `KZ_Status` int(4) unsigned zerofill NOT NULL DEFAULT '0000',
  `Fehlercode` int(4) unsigned zerofill NOT NULL DEFAULT '0000',
  `Erzeugerstation` char(4) NOT NULL DEFAULT '',
  `Text` char(200) DEFAULT NULL,
  `Wartezeit` char(2) DEFAULT NULL,
  `Exportstation` char(4) NOT NULL DEFAULT '',
  `Frei1` char(1) DEFAULT NULL,
  `Infotext` char(11) DEFAULT NULL,
  `Frei2` char(2) DEFAULT NULL,
  `uebertragen` int(1) DEFAULT '0',
  `Timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Timestamp2` datetime DEFAULT NULL,
  `Zaehler` int(11) NOT NULL AUTO_INCREMENT,
  `UploadStatus` tinyint(4) NOT NULL DEFAULT '0',
  `SendStatus` tinyint(4) NOT NULL DEFAULT '0',
  `OrderIDSta` double DEFAULT NULL,
  `poslong` double DEFAULT NULL,
  `poslat` double DEFAULT NULL,
  PRIMARY KEY (`Zaehler`),
  UNIQUE KEY `Zaehler` (`Zaehler`),
  KEY `kzstatus` (`KZ_Status`),
  KEY `erzeugerstation` (`Erzeugerstation`),
  KEY `Packstuecknummer` (`Packstuecknummer`),
  KEY `Fehlercode` (`Fehlercode`),
  KEY `KZ_Statuserzeuger` (`KZ_Statuserzeuger`),
  KEY `timestamp2` (`Timestamp2`),
  KEY `SendStatus` (`SendStatus`),
  KEY `Datum` (`Datum`),
  KEY `Zeit` (`Zeit`),
  KEY `OrderIDSta` (`OrderIDSta`)
) ENGINE=InnoDB AUTO_INCREMENT=253361748 DEFAULT CHARSET=latin1;

CREATE TABLE `tblstatus_trx` (
  `KZ_Statuserzeuger` char(1) NOT NULL DEFAULT 'E',
  `Packstuecknummer` double unsigned zerofill NOT NULL DEFAULT '0000000000000000000000',
  `Datum` char(8) NOT NULL DEFAULT '',
  `Zeit` char(8) NOT NULL DEFAULT '',
  `KZ_Status` int(4) unsigned zerofill NOT NULL DEFAULT '0000',
  `Fehlercode` int(4) unsigned zerofill NOT NULL DEFAULT '0000',
  `Erzeugerstation` char(4) NOT NULL DEFAULT '',
  `Text` char(200) DEFAULT NULL,
  `Wartezeit` char(2) DEFAULT NULL,
  `Exportstation` char(4) NOT NULL DEFAULT '',
  `Frei1` char(1) DEFAULT NULL,
  `Infotext` char(11) DEFAULT NULL,
  `Frei2` char(2) DEFAULT NULL,
  `uebertragen` int(1) DEFAULT '0',
  `Timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Timestamp2` datetime DEFAULT NULL,
  `Zaehler` int(11) NOT NULL AUTO_INCREMENT,
  `UploadStatus` tinyint(4) NOT NULL DEFAULT '0',
  `SendStatus` tinyint(4) NOT NULL DEFAULT '0',
  `OrderIDSta` double DEFAULT NULL,
  `poslong` double DEFAULT NULL,
  `poslat` double DEFAULT NULL,
  PRIMARY KEY (`Zaehler`),
  UNIQUE KEY `Zaehler` (`Zaehler`),
  KEY `kzstatus` (`KZ_Status`),
  KEY `erzeugerstation` (`Erzeugerstation`),
  KEY `Packstuecknummer` (`Packstuecknummer`),
  KEY `Fehlercode` (`Fehlercode`),
  KEY `KZ_Statuserzeuger` (`KZ_Statuserzeuger`),
  KEY `timestamp2` (`Timestamp2`),
  KEY `SendStatus` (`SendStatus`),
  KEY `Datum` (`Datum`),
  KEY `Zeit` (`Zeit`),
  KEY `OrderIDSta` (`OrderIDSta`)
) ENGINE=InnoDB AUTO_INCREMENT=253361748 DEFAULT CHARSET=latin1;
