use dekuclient;
ALTER TABLE claresultruns
ADD COLUMN sysov DOUBLE NOT NULL DEFAULT 0 ,
ADD COLUMN sysovperct DOUBLE NOT NULL DEFAULT 0 ;

ALTER TABLE clareklapositionen
ADD COLUMN sysov DOUBLE NOT NULL DEFAULT 0 ,
ADD COLUMN sysovperct DOUBLE NOT NULL DEFAULT 0 ;

ALTER TABLE clamanuelleartikel
ADD COLUMN sysovperct DOUBLE NOT NULL DEFAULT 0;
