USE dekuclient;

CREATE TABLE `hubcounttmp` (
  `ES`              VARCHAR(255) DEFAULT NULL,
  `OrderID`         DOUBLE       DEFAULT NULL,
  `Belegnummer`     DOUBLE       DEFAULT NULL,
  `DepotNrAD`       INT(11)      DEFAULT NULL,
  `DepotNrLD`       INT(11)      DEFAULT NULL,
  `DepotNrZD`       INT(11)      DEFAULT NULL,
  `lockflag`        SMALLINT(6)  DEFAULT NULL,
  `dtCreateAD`      DATETIME     DEFAULT NULL,
  `KZ_Transportart` SMALLINT(6)  DEFAULT NULL,
  `Verladedatum`    DATETIME     DEFAULT NULL,
  `DepotNrAbD`      INT(11)      DEFAULT NULL,
  `CollieBelegNr`   DOUBLE       DEFAULT NULL,
  `OrderPos`        SMALLINT(6)  DEFAULT NULL,
  `Laenge`          SMALLINT(6)  DEFAULT NULL,
  `Breite`          SMALLINT(6)  DEFAULT NULL,
  `Hoehe`           SMALLINT(6)  DEFAULT NULL,
  `GewichtReal`     DOUBLE       DEFAULT NULL,
  `GewichtEffektiv` DOUBLE       DEFAULT NULL,
  `GewichtLBH`      DOUBLE       DEFAULT NULL,
  `verladelinie`    DOUBLE       DEFAULT NULL,
  `dtAusgangHup3`   DATETIME     DEFAULT NULL,
  `dtEingangHup3`   DATETIME     DEFAULT NULL,
  `dtAusgangDepot2` DATETIME     DEFAULT NULL,
  `dtEingangDepot2` DATETIME     DEFAULT NULL,
  `mydepotid2`      INT(11)      DEFAULT NULL,
  `BagBelegNrC`     DOUBLE       DEFAULT NULL,
  `BagBelegNrAbC`   DOUBLE       DEFAULT NULL,
  `timestamp`       DATETIME     DEFAULT NULL,
  KEY `pk` (`OrderID`),
  KEY `verladedatum` (`Verladedatum`),
  KEY `dtausgangdepot2` (`dtAusgangDepot2`),
  KEY `dtEingangHup3` (`dtEingangHup3`),
  KEY `verladelinie` (`verladelinie`),
  KEY `DepotNrAbD` (`DepotNrAbD`),
  KEY `DepotNrLD` (`DepotNrLD`),
  KEY `timestamp` (`timestamp`),
  KEY `BagBelegNrC` (`BagBelegNrC`),
  KEY `CollieBelegNr` (`CollieBelegNr`),
  KEY `BagBelegNrAbC` (`BagBelegNrAbC`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = latin1;
