ALTER TABLE mst_key DROP PRIMARY KEY;
ALTER TABLE mst_key
  ALTER COLUMN id IDENTITY;

ALTER TABLE mst_user DROP PRIMARY KEY;
ALTER TABLE mst_user
  ALTER COLUMN id IDENTITY;

ALTER TABLE mst_station_user DROP PRIMARY KEY;
ALTER TABLE mst_station_user
  ALTER COLUMN id IDENTITY;
