CREATE TABLE mst_country (
  CODE         VARCHAR   NOT NULL,
  MAXLEN       INTEGER,
  MINLEN       INTEGER,
  NAMESTRINGID INTEGER,
  ROUTINGTYP   INTEGER,
  TIMESTAMP    TIMESTAMP NOT NULL,
  ZIPFORMAT    VARCHAR,
  PRIMARY KEY (CODE)
);
CREATE TABLE mst_holidayctrl (
  COUNTRY     VARCHAR   NOT NULL,
  HOLIDAY     TIMESTAMP NOT NULL,
  CTRLPOS     INTEGER,
  DESCRIPTION VARCHAR,
  TIMESTAMP   TIMESTAMP NOT NULL,
  PRIMARY KEY (COUNTRY, HOLIDAY)
);
CREATE TABLE mst_route (
  COUNTRY     VARCHAR   NOT NULL,
  VALIDCRTR   INTEGER   NOT NULL,
  VALIDFROM   TIMESTAMP NOT NULL,
  LAYER       INTEGER   NOT NULL,
  ZIPFROM     VARCHAR   NOT NULL,
  AREA        VARCHAR,
  ETOD        TIME,
  HOLIDAYCTRL VARCHAR,
  ISLAND      INTEGER,
  LTODHOLIDAY TIME,
  LTODSA      TIME,
  LTOP        TIME,
  SATURDAYOK  INTEGER,
  STATION     INTEGER,
  TERM        INTEGER,
  TIMESTAMP   TIMESTAMP NOT NULL,
  VALIDTO     TIMESTAMP,
  ZIPTO       VARCHAR,
  PRIMARY KEY (COUNTRY, VALIDCRTR, VALIDFROM, LAYER, ZIPFROM)
);
CREATE INDEX INDEX_mst_route_LAYER ON mst_route (LAYER);
CREATE INDEX INDEX_mst_route_TIMESTAMP ON mst_route (TIMESTAMP);
CREATE TABLE mst_routinglayer (
  LAYER       INTEGER   NOT NULL,
  DESCRIPTION VARCHAR,
  SERVICES    INTEGER,
  TIMESTAMP   TIMESTAMP NOT NULL,
  PRIMARY KEY (LAYER)
);
CREATE TABLE mst_sector (
  SECTORTO   VARCHAR   NOT NULL,
  SECTORFROM VARCHAR   NOT NULL,
  VALIDFROM  TIMESTAMP NOT NULL,
  TIMESTAMP  TIMESTAMP NOT NULL,
  VALIDTO    TIMESTAMP,
  VIA        VARCHAR,
  PRIMARY KEY (SECTORTO, SECTORFROM, VALIDFROM)
);
CREATE TABLE mst_station (
  STATIONNR       INTEGER   NOT NULL,
  ADDRESS1        VARCHAR,
  ADDRESS2        VARCHAR,
  BILLINGADDRESS1 VARCHAR,
  BILLINGADDRESS2 VARCHAR,
  BILLINGCITY     VARCHAR,
  BILLINGCOUNTRY  VARCHAR,
  BILLINGHOUSENR  VARCHAR,
  BILLINGSTREET   VARCHAR,
  BILLINGZIP      VARCHAR,
  CITY            VARCHAR,
  CONTACTPERSON1  VARCHAR,
  CONTACTPERSON2  VARCHAR,
  COUNTRY         VARCHAR,
  EMAIL           VARCHAR,
  HOUSENR         VARCHAR,
  MOBILE          VARCHAR,
  PHONE1          VARCHAR,
  PHONE2          VARCHAR,
  POSLAT          DOUBLE,
  POSLONG         DOUBLE,
  SECTOR          VARCHAR,
  SERVICEPHONE1   VARCHAR,
  SERVICEPHONE2   VARCHAR,
  STRANG          INTEGER,
  STREET          VARCHAR,
  TELEFAX         VARCHAR,
  TIMESTAMP       TIMESTAMP NOT NULL,
  USTID           VARCHAR,
  WEBADDRESS      VARCHAR,
  ZIP             VARCHAR,
  PRIMARY KEY (STATIONNR)
);
CREATE TABLE mst_station_sector (
  STATIONNR    INTEGER NOT NULL,
  SECTOR       VARCHAR NOT NULL,
  ROUTINGLAYER INTEGER,
  TIMESTAMP    TIMESTAMP,
  PRIMARY KEY (STATIONNR, SECTOR)
);
CREATE TABLE sys_property (
  STATION     INTEGER NOT NULL,
  ID          INTEGER NOT NULL,
  DESCRIPTION VARCHAR,
  ENABLED     BOOLEAN,
  TIMESTAMP   TIMESTAMP,
  VALUE       VARCHAR,
  PRIMARY KEY (STATION, ID)
);
