USE `dekuclient`;

CREATE TABLE `sdd_fpcs_order` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `customers_reference` VARCHAR(100) NOT NULL COMMENT '',
  `gls_parcelno` DOUBLE NULL COMMENT '',
  `customer_no` VARCHAR(45) NOT NULL COMMENT '',
  `contact_no` VARCHAR(45) NOT NULL COMMENT '',
  `zipcode_ref` INT NULL COMMENT '',
  `name_from` VARCHAR(45) NOT NULL COMMENT '',
  `name2_from` VARCHAR(45) NULL COMMENT '',
  `name3_from` VARCHAR(45) NULL COMMENT '',
  `street_from` VARCHAR(45) NOT NULL COMMENT '',
  `streetno_from` VARCHAR(45) NULL COMMENT '',
  `city_from` VARCHAR(45) NOT NULL COMMENT '',
  `country_from` VARCHAR(45) NOT NULL COMMENT '',
  `zip_from` VARCHAR(45) NOT NULL COMMENT '',
  `name_to` VARCHAR(45) NOT NULL COMMENT '',
  `name2_to` VARCHAR(45) NULL COMMENT '',
  `name3_to` VARCHAR(45) NULL COMMENT '',
  `street_to` VARCHAR(45) NOT NULL COMMENT '',
  `streetno_to` VARCHAR(10) NULL COMMENT '',
  `city_to` VARCHAR(45) NOT NULL COMMENT '',
  `country_to` VARCHAR(45) NOT NULL COMMENT '',
  `zip_to` VARCHAR(45) NOT NULL COMMENT '',
  `mail_address` VARCHAR(45) NULL COMMENT '',
  `processed_state` INT NULL DEFAULT 0 COMMENT '',
  `dt_ship` DATE NOT NULL COMMENT '',
  `ts_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `cancel_requested` INT NOT NULL DEFAULT 0 COMMENT '',
  `ts_canceled` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '');
